# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Container Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pyyaml safety liccheck bandit
    - name: Container Security
      run: |
        wget https://downloads.cisofy.com/lynis/lynis-2.7.5.tar.gz && ls -lrt && tar -xfvz lynis-2.7.5.tar.gz -C ~/
        ~/lynis audit dockerfile ./Dockerfile
   
